### 
POST http://localhost:3333/products
Content-Type: application/json

{
  "name" : "kaiak",
  "description": "perfume masculino",
  "image": "ajsdopajsopd",
  "type": "perfume",
  "gender": "M",
  "size": 100,
  "expirationDate": "01/2023"
}